### ISSUE TITLE
SD：I can't find the file of choose_first_channel.sh in the script file(run.sh,line34), whether this step is necessary? can i delete this line?

### ISSUE THREAD

**Issue by MQQ1996** [MagicHub-io/Magic-Data-ASR-SD-Challenge#1]

**Comment by CYFFF** [comment]
Thanks for comment, and we fix this bug by replacing it by:

cp $work_dir/init_wav.scp $work_dir/wav.scp
awk '{print $1" "$1}' $work_dir/wav.scp > $work_dir/utt2spk
awk '{print $1" "$1}' $work_dir/wav.scp > $work_dir/spk2utt

We already update the repository.
