### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by LONG520520** [MagicHub-io/Magic-Data-ASR-SD-Challenge#10]
可以在哪里得到160小时的数据集？
谢谢大佬

**Comment by CYFFF** [comment]
如果没参加比赛的话，就目前而言是没有办法得到。但我们打算在比赛彻底结束之后，将整个数据集公开，将和之前的数据集 [MAGICDATA Mandarin Chinese Read Speech Corpus (openslr-68) ](http://www.openslr.org/68/)  一样放在 openslr  上，欢迎关注我们的后续工作。

**Comment by LONG520520** [comment]
好的，非常感谢

**Comment by LONG520520** [comment]
已收到回复，非常感谢。国内有这样的比赛，都我们这个研究领域非常有帮助，希望下次可以参加比赛，同时也想问一下下一届比赛的网址是否可以提供一下，十分感谢。
















在 2021-09-14 22:36:42，"CYF" ***@***.***> 写道：

如果没参加比赛的话，就目前而言是没有办法得到。但我们打算在比赛彻底结束之后，将整个数据集公开，将和之前的数据集 MAGICDATA Mandarin Chinese Read Speech Corpus (openslr-68) 一样放在 openslr 上，欢迎关注我们的后续工作。

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
