### ISSUE TITLE
Method about changing the dimensions of embedding

### ISSUE THREAD

**Issue by axuan731** [MagicHub-io/Magic-Data-ASR-SD-Challenge#12]
hello,when I try to change the dimension of emb, I modify the parameters of predict.py as follows:

parser.add_argument('--embed-dim', required=False, type=int, default=512, help='dimensionality of the emb')

and the error log shows:

Traceback (most recent call last):
  File "VBx/vbhmm.py", line 133, in <module>
    fea = (x - plda_mu).dot(plda_tr.T)[:, :args.lda_dim]
ValueError: operands could not be broadcast together with shapes (2576,512) (128,) 

when I run the program again, I dont receive the error log, but the result of diarization output are same as  the dimensions of 256 or 128... I wanna know is that a ture result? Why it doesn't change the result at all?
Thanks very much for ur reply!!!

**Comment by CYFFF** [comment]
emmm, , , plda_mu and plda_tr  are from VBx/models/ResNet101_16kHz/plda.  Maybe 512-dimension embedding is not matched with the pre-trained PLDA value?  If you change your embeddings, you need train PLDA with a matched dimension. Please refer to [VBx-training Script](https://github.com/CYFFF/VBx-training-dist/blob/main/run.sh) Line 173.

**Comment by axuan731** [comment]
Thanks！！！
