### ISSUE TITLE
SD:I want to use the gpu to extract embedding and i can't find the file of  scripts/extract_embeddings_gpu.sh in the run.sh(line72)

### ISSUE THREAD

**Issue by MQQ1996** [MagicHub-io/Magic-Data-ASR-SD-Challenge#2]

**Comment by CYFFF** [comment]
The code repo has been updated to support gpu inference.  It uses Pytorch to extract embedding on gpu. And you should firstly prepare VBx/models/ResNet101_16kHz/nnet/raw_81.pth by unzip raw_81.pth.zip* together. For more information, you could also refer to [VBx-training-recipe](https://github.com/phonexiaresearch/VBx-training-recipe) and [VBx](https://github.com/BUTSpeechFIT/VBx/)  (p.s. ONNX is faster usually, even though it uses cpus only.)
