### ISSUE TITLE
SD: method about the speaker embedding cluster

### ISSUE THREAD

**Issue by axuan731** [MagicHub-io/Magic-Data-ASR-SD-Challenge#4]
when I do the speaker embedding cluster（step 4）, the job was failed and I look up the fail log. It shows that “OSError: ./data/magicdata160h_dev_test/dia_part/embedding/CTS-CN-F2F-2019-11-15-****.seg not found.“ Thanks for solving my problem.^_^

**Comment by axuan731** [comment]
# python VBx/vbhmm.py --init AHC+VB --out-rttm-dir ./data/magicdata160h_dev_test/dia_part/rttm --xvec-ark-file ./data/magicdata160h_dev_test/dia_part/embedding/CTS-CN-F2F-2019-11-15-160.ark --segments-file ./data/magicdata160h_dev_test/dia_part/embedding/CTS-CN-F2F-2019-11-15-160.seg --xvec-transform VBx/models/ResNet101_16kHz/transform.h5 --plda-file VBx/models/ResNet101_16kHz/plda --threshold -0.015 --lda-dim 128 --Fa 0.3 --Fb 17 --loopP 0.99 
# Started at Wed Aug 18 21:22:13 CST 2021
#
Traceback (most recent call last):
  File "VBx/vbhmm.py", line 90, in <module>
    segs_dict = read_xvector_timing_dict(args.segments_file)
  File "/home/duyuxuan/Magic-Data-ASR-SD-Challenge-main/sd/VBx/diarization_lib.py", line 138, in read_xvector_timing_dict
    segs = np.loadtxt(kaldi_segments, dtype=object)
  File "/usr/local/lib/python3.8/dist-packages/numpy/lib/npyio.py", line 1067, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/usr/local/lib/python3.8/dist-packages/numpy/lib/_datasource.py", line 193, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/usr/local/lib/python3.8/dist-packages/numpy/lib/_datasource.py", line 533, in open
    raise IOError("%s not found." % path)
OSError: ./data/magicdata160h_dev_test/dia_part/embedding/CTS-CN-F2F-2019-11-15-160.seg not found.
# Accounting: time=18 threads=1
# Ended (code 1) at Wed Aug 18 21:22:31 CST 2021, elapsed time 18 seconds

**Comment by axuan731** [comment]
# python VBx/vbhmm.py --init AHC+VB --out-rttm-dir ./data/magicdata160h_dev_test/dia_part/rttm --xvec-ark-file ./data/magicdata160h_dev_test/dia_part/embedding/CTS-CN-F2F-2019-11-15-160.ark --segments-file ./data/magicdata160h_dev_test/dia_part/embedding/CTS-CN-F2F-2019-11-15-160.seg --xvec-transform VBx/models/ResNet101_16kHz/transform.h5 --plda-file VBx/models/ResNet101_16kHz/plda --threshold -0.015 --lda-dim 128 --Fa 0.3 --Fb 17 --loopP 0.99 
# Started at Wed Aug 18 21:22:13 CST 2021
#
Traceback (most recent call last):
  File "VBx/vbhmm.py", line 90, in <module>
    segs_dict = read_xvector_timing_dict(args.segments_file)
  File "/home/duyuxuan/Magic-Data-ASR-SD-Challenge-main/sd/VBx/diarization_lib.py", line 138, in read_xvector_timing_dict
    segs = np.loadtxt(kaldi_segments, dtype=object)
  File "/usr/local/lib/python3.8/dist-packages/numpy/lib/npyio.py", line 1067, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/usr/local/lib/python3.8/dist-packages/numpy/lib/_datasource.py", line 193, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/usr/local/lib/python3.8/dist-packages/numpy/lib/_datasource.py", line 533, in open
    raise IOError("%s not found." % path)
OSError: ./data/magicdata160h_dev_test/dia_part/embedding/CTS-CN-F2F-2019-11-15-160.seg not found.
# Accounting: time=18 threads=1
# Ended (code 1) at Wed Aug 18 21:22:31 CST 2021, elapsed time 18 seconds

**Comment by CYFFF** [comment]
Thanks for opening issue. This is because X-vector embedding are calculating in the background and not finished. We split run.sh into two parts, i.e. run_extracting_embedding.sh and run_clustering.sh. Try to execute run_extracting_embedding.sh firstly and wait for all embedding calculating tasks to the end. Then execute run_clustering.sh.
