### ISSUE TITLE
if the process of embedding extracting and clustering use all cpu threads？ can you give me a suggestion to set the number of cpu threads by myself，thank you very much.

### ISSUE THREAD

**Issue by MQQ1996** [MagicHub-io/Magic-Data-ASR-SD-Challenge#6]

**Comment by CYFFF** [comment]
ok，i'll provide scripts that use less threads later.

**Comment by CYFFF** [comment]
The repo has been updated. In VBx/predict.py line 129,  sess_options.intra_op_num_threads  could control the number of cpu threads.

**Comment by CYFFF** [comment]
And the embeddings are calculated one-by-one now.
