### ISSUE TITLE
i want to know the result of the vbx from the data of train or test(source from magicdate_160h by prepare_magicdata_160h.py)

### ISSUE THREAD

**Issue by MQQ1996** [MagicHub-io/Magic-Data-ASR-SD-Challenge#7]

**Comment by CYFFF** [comment]
When you run prepare_magicdata_160h.py, rttm_gt_test and rttm_gt_train are generated. They are groundtruth of magicdata_160h. I don't know whether I get your point.

**Comment by MQQ1996** [comment]
the content of the rttm illustrates the splits of data(train or test) and whether i can consider the&nbsp;magicdata_160h that can be divided into train set and test set according to the&nbsp;&nbsp;rttm_gt_test and rttm_gt_train? And then i can get two results from train set and test set by embedding extracting and clustering,&nbsp; and&nbsp; i want to know the result of vbx is the result of test set?







------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月26日(星期四) 上午10:17
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [MagicHub-io/Magic-Data-ASR-SD-Challenge] i want to know the result of the vbx from the data of train or test(source from magicdate_160h by prepare_magicdata_160h.py) (#7)





 
When you run prepare_magicdata_160h.py, rttm_gt_test and rttm_gt_train are generated. They are groundtruth of magicdata_160h. I don't know whether I get your point.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by CYFFF** [comment]
yes, vbx is the result of test set.

**Comment by CYFFF** [comment]
However, this result is just for reference (or valid).  When test set of challenge is released, you may submit results of that  test set.

**Comment by MQQ1996** [comment]
all right, thank you!
