### ISSUE TITLE
Method regarding dscore

### ISSUE THREAD

**Issue by axuan731** [MagicHub-io/Magic-Data-ASR-SD-Challenge#9]
您好，打分的代码为python score.py --collar 0.25 -r ${groundtruth_rttm} -s ${predicted_rttm}
其中groundtruth的rttm在scripts/rttm_gt_train为一个文件。predicted的rttm在dia_part/rttm下包含三百多个文件，我是否需要自己把所有的文件合并才能进行打分？在项目中是否有合并文件的脚本？对打分这里不太理解，还想请教您，感谢！

**Comment by CYFFF** [comment]
需要合并  cat ./data/magicdata160h_dev_test/dia_part/rttm/* > magicdata_predicted_rttm

**Comment by CYFFF** [comment]
拿这个 magicdata_predicted_rttm 打分

**Comment by CYFFF** [comment]
三百多个文件，，，emmm，，这怕是把训练集也跑了一遍，其实只需要跑划出来的验证集就行，这个验证集的大小和比赛到时候放出来的测试集差不多

**Comment by axuan731** [comment]
感谢 都OK了

**Comment by CYFFF** [comment]
不客气
